# If the listeners should be enabled
# The /jw reload command will be valid
enable: true

# The URL for the discord webhook
webhookURL: " "

# Use FIELDS (for different fields) or DESCRIPTION (for one whole message as description)
format: "FIELDS"

# Commands on which to listen and get arguments
commands:
  jail: "jail"
  unjail: "unjail"

# The permission, needed for the /jail and /unjail commands (security reasons)
# If no permission needed, leave blank space -> " "
permissions:
  jail: " "
  unjail: " "

# Text to show when there is no specified
# reason in the command arguments
no-reason-specified: "Не е посочена причина"

# Title of the embed
title:
  # %nickname% -> gets the name of the jailed player
  enable: true
  text: "Нов затворник - %nickname%"

# For embed with fields (option format: FIELDS)
# Group names doesn't matter (reason, duration etc.)
# Text order and content can be changed at wish
fields:

  # %reason% -> gets the reason for the jail (no, it doesn't return null) :D
  reason:
    enable: true
    title: "Причина"
    field: "%reason%"

  # %duration% -> gets the duration of the jail
  duration:
    enable: true
    title: "Време"
    field: "%duration%"

  # %cell% -> gets the number of the cell that the player is jailed in
  cell:
    enable: true
    title: "Килия"
    field: "%cell%"

  # %lockedBy% -> gets the name of the staff member who jailed the player
  lockedBy:
    enable: true
    title: "Заключен от"
    field: "%lockedBy%"

# For embed with description (option format: DESCRIPTION)
description:
  # Handles all of the above placeholders
  # For new line: \n
  text: ""

# Timestamp info
timeStamp:
  enable: true
  format: "HH:mm:ss dd-MM-yyyy"

  # For translation in the duration of the jail
  day: "ден"
  hour: "час"
  minute: "минута"
  second: "секунда"
  days: "дни"
  hours: "часа"
  minutes: "минути"
  seconds: "секунди"

# For the color of the embed (needs HEX colors)
color: "#E83842"

# Info for the database
database:
  address: " "
  database: " "
  username: " "
  password: " "
  table: " "

  # Time difference between the database and the system
  # You can check it by executing
  # SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);
  # in the database manager
  # If it's 3:30:00 type: 3.5
  time-difference: " "

  # The period for updating the active state of a jail
  # Could be 1 SECOND, 15 MINUTE, 2 HOUR etc.
  update-period: " "