main: "JailWebhook"
name: "JailWebhook"
author: "Proto68"
api-version: 1.20
version: 1.0

commands:
  jw:
    description: Base command for the JW plugin.
    usage: /<command> <subcommand>

permissions:
  jailwebhook.reload:
    description: Allows the user to reload the JailWebhook configuration.
    default: op